### ISSUE TITLE
Firefox compatibility + Dice texture specification

### ISSUE THREAD

**Issue by ebalmeida** [tobloef/roll20-fancy-dice#5]
Hi, no actual issues. Half suggestion and half question:
- Do you have plans to make the extension firefox compatible? Since the chrome store took down VTTes I think many power roll20 users will end up migrating.
- On this end, I noticed it's incompatible with VTTes right now. Any plans to make them play nice together?
- Do you have any specifications to the texture images? In particular the roll20 color compatible ones? From what I've seen you use black and white in a manner similar to an alpha mask. Would grays work as partial transparency for the user color as well? Would other colors work or would they mean lost compatibility?

**Comment by tobloef** [comment]
Hey there.

- I would very much like to make it Firefox compatible and I think it's doable without too much of a hassle.
- I've noticed the thing with VTTes as well, but I'm not sure where to start in making them play nicer. I guess it's something to do with how scripts are injected, but I don't know enough about VTTes to guess at how to do it in a non-interfering manner. 
- The way Roll20 handles dice textures and color by default is to tint the texture with the player's color in what I think is a Multiply blend mode. This means that the lighter a part is, the more of the color it will receive. White will completely be the color, black will just stay black. Gray would be a sort of darkish version of the color. You can also have transparency in the texture, that will work just fine, and you will be able to see right through the dice. But it looks a bit weird, due it only being visible from one side. Other colors work alright, as long as the Roll20 player color is white, else they will be tinted. This is how the fancy D6 test works, that's just an image texture with the dice color set to always be white no matter the player color.

I have been thinking about experimenting with multiple layers of textures, with different colors, so you can have two or more customizable colors on a dice instead of just one, but I've had no success yet. I think it is doable, but other life stuff has gotten in the way of this project.

**Comment by ebalmeida** [comment]
Huh...
I code, maybe I could look into it. I just never worked with browser extensions. Can you point me towards a resource that will help me figure out how to test this code in a browser?

**Comment by tobloef** [comment]
I've been slowly working on a guide on how to contribute to the project. You can view a half-finished rough draft here: [https://github.com/tobloef/roll20-fancy-dice/wiki/How-to-add-your-own-dice-to-the-extension](https://github.com/tobloef/roll20-fancy-dice/wiki/How-to-add-your-own-dice-to-the-extension)

**Comment by ebalmeida** [comment]
That's great. Thanks, I'll take a look and see if there's anything I can think of to help.
